/**
 * Created by ismaro3 on 16/08/17.
 */
'use strict';

const languages = [
    { tag: 'ar', name: 'Arabic' },
    { tag: 'az', name: 'Azeri' },
    { tag: 'be', name: 'Belarusian' },
    { tag: 'bg', name: 'Bulgarian' },
    { tag: 'bn', name: 'Malay (Brunei Darussalam)' },
    { tag: 'ca', name: 'Catalan' },
    { tag: 'commons', name: 'Commons' },
    { tag: 'cs', name: 'Czech' },
    { tag: 'cy', name: 'Welsh' },
    { tag: 'da', name: 'Danish' },
    { tag: 'de', name: 'German' },
    { tag: 'el', name: 'Greek' },
    { tag: 'en', name: 'English' },
    { tag: 'eo', name: 'Esperanto' },
    { tag: 'es', name: 'Spanish' },
    { tag: 'et', name: 'Estonian' },
    { tag: 'eu', name: 'Basque' },
    { tag: 'fa', name: 'Farsi' },
    { tag: 'fi', name: 'Finnish' },
    { tag: 'fr', name: 'French' },
    { tag: 'ga', name: 'Irish' },
    { tag: 'gl', name: 'Galician' },
    { tag: 'hi', name: 'Hindi' },
    { tag: 'hr', name: 'Croatian' },
    { tag: 'hu', name: 'Hungarian' },
    { tag: 'hy', name: 'Armenian' },
    { tag: 'id', name: 'Indonesian' },
    { tag: 'it', name: 'Italian' },
    { tag: 'ja', name: 'Japanese' },
    { tag: 'ko', name: 'Korean' },
    { tag: 'lt', name: 'Lithuanian' },
    { tag: 'lv', name: 'Latvian' },
    { tag: 'mk', name: 'Macedonian' },
    { tag: 'mt', name: 'Maltese' },
    { tag: 'nl', name: 'Dutch' },
    { tag: 'pl', name: 'Polish' },
    { tag: 'pt', name: 'Portuguese' },
    { tag: 'ro', name: 'Romanian' },
    { tag: 'ru', name: 'Russian' },
    { tag: 'sk', name: 'Slovak' },
    { tag: 'sl', name: 'Slovenian' },
    { tag: 'sr', name: 'Serbian' },
    { tag: 'sv', name: 'Swedish' },
    { tag: 'tr', name: 'Turkish' },
    { tag: 'uk', name: 'Ukrainian' },
    { tag: 'ur', name: 'Urdu' },
    { tag: 'vi', name: 'Vietnamese' },
    { tag: 'war', name: 'War' },
    { tag: 'zh', name: 'Chinese' }
];
module.exports = languages;
